category: GAMES_AND_TRIVIA
defaultLocale: en
localizedSettings:
  displayName: Interactive canvas sample
  pronunciation: Interactive canvas sample
projectId: essence-helper
usesInteractiveCanvas: true
