exports.strings = {
  LAUNCH: 'Hello Zenithian. I can get you the effects of an equipment perk or the location of a cooking ingredient. Which one would you like to know?',
  PERK: '{{perkName}} is {{indefiniteArticle}} {{perkType}} perk with the following effect: {{perkEffect}}',
  SOURCE: '{{sourceText}}',
  ASK_FOR_PERK: 'Please, provide the name of an equipment perk.',
  ASK_FOR_DISCOVERABLE: 'Please, provide the name of a cooking ingredient.',
  UNKNOWN_PERK_EFFECT: 'The effect for this perk is currently unknown.',
  UNKNOWN_SOURCE: 'The location for this item is currently unknown.',
  ACCORDING_TO_SOURCE: 'According to {{source}}',
  PERK_NOT_FOUND: 'I could not find a perk with this name. Please try again.',
  ITEM_NOT_FOUND: 'I could not find an item with this name. Please try again.',
  SKILL_NAME: 'Essence Helper',
  HELP: 'I can get you the effects of an equipment perk or the location of a cooking ingredient.',
  FALLBACK: "Sorry, I don't know that. Try again.",
  ERROR: "Sorry, I didn't understand. Try again.",
}